/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.
import { Route as rootRouteImport } from './routes/__root';
import { Route as BattleIndexRouteImport } from './routes/battle/index';
import { Route as IndexRouteImport } from './routes/index';
import { Route as LearningIndexRouteImport } from './routes/learning/index';
import { Route as LearningQuestionRouteImport } from './routes/learning/question';
import { Route as MypageIndexRouteImport } from './routes/mypage/index';
import { Route as RankingIndexRouteImport } from './routes/ranking/index';

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any);
const RankingIndexRoute = RankingIndexRouteImport.update({
  id: '/ranking/',
  path: '/ranking/',
  getParentRoute: () => rootRouteImport,
} as any);
const MypageIndexRoute = MypageIndexRouteImport.update({
  id: '/mypage/',
  path: '/mypage/',
  getParentRoute: () => rootRouteImport,
} as any);
const LearningIndexRoute = LearningIndexRouteImport.update({
  id: '/learning/',
  path: '/learning/',
  getParentRoute: () => rootRouteImport,
} as any);
const BattleIndexRoute = BattleIndexRouteImport.update({
  id: '/battle/',
  path: '/battle/',
  getParentRoute: () => rootRouteImport,
} as any);
const LearningQuestionRoute = LearningQuestionRouteImport.update({
  id: '/learning/question',
  path: '/learning/question',
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/learning/question': typeof LearningQuestionRoute;
  '/battle': typeof BattleIndexRoute;
  '/learning': typeof LearningIndexRoute;
  '/mypage': typeof MypageIndexRoute;
  '/ranking': typeof RankingIndexRoute;
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/learning/question': typeof LearningQuestionRoute;
  '/battle': typeof BattleIndexRoute;
  '/learning': typeof LearningIndexRoute;
  '/mypage': typeof MypageIndexRoute;
  '/ranking': typeof RankingIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/': typeof IndexRoute;
  '/learning/question': typeof LearningQuestionRoute;
  '/battle/': typeof BattleIndexRoute;
  '/learning/': typeof LearningIndexRoute;
  '/mypage/': typeof MypageIndexRoute;
  '/ranking/': typeof RankingIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: '/' | '/learning/question' | '/battle' | '/learning' | '/mypage' | '/ranking';
  fileRoutesByTo: FileRoutesByTo;
  to: '/' | '/learning/question' | '/battle' | '/learning' | '/mypage' | '/ranking';
  id:
    | '__root__'
    | '/'
    | '/learning/question'
    | '/battle/'
    | '/learning/'
    | '/mypage/'
    | '/ranking/';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  LearningQuestionRoute: typeof LearningQuestionRoute;
  BattleIndexRoute: typeof BattleIndexRoute;
  LearningIndexRoute: typeof LearningIndexRoute;
  MypageIndexRoute: typeof MypageIndexRoute;
  RankingIndexRoute: typeof RankingIndexRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/ranking/': {
      id: '/ranking/';
      path: '/ranking';
      fullPath: '/ranking';
      preLoaderRoute: typeof RankingIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/mypage/': {
      id: '/mypage/';
      path: '/mypage';
      fullPath: '/mypage';
      preLoaderRoute: typeof MypageIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/learning/': {
      id: '/learning/';
      path: '/learning';
      fullPath: '/learning';
      preLoaderRoute: typeof LearningIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/battle/': {
      id: '/battle/';
      path: '/battle';
      fullPath: '/battle';
      preLoaderRoute: typeof BattleIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/learning/question': {
      id: '/learning/question';
      path: '/learning/question';
      fullPath: '/learning/question';
      preLoaderRoute: typeof LearningQuestionRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LearningQuestionRoute: LearningQuestionRoute,
  BattleIndexRoute: BattleIndexRoute,
  LearningIndexRoute: LearningIndexRoute,
  MypageIndexRoute: MypageIndexRoute,
  RankingIndexRoute: RankingIndexRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
