/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as MainRouteImport } from './routes/_main'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as PublicRegisterRouteImport } from './routes/_public/register'
import { Route as PublicLoginRouteImport } from './routes/_public/login'
import { Route as MainRankingIndexRouteImport } from './routes/_main/ranking/index'
import { Route as MainMypageIndexRouteImport } from './routes/_main/mypage/index'
import { Route as MainLearningIndexRouteImport } from './routes/_main/learning/index'
import { Route as MainBattleIndexRouteImport } from './routes/_main/battle/index'
import { Route as MainLearningQuestionRouteImport } from './routes/_main/learning/question'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const MainRoute = MainRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicRegisterRoute = PublicRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => PublicRoute,
} as any)
const PublicLoginRoute = PublicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicRoute,
} as any)
const MainRankingIndexRoute = MainRankingIndexRouteImport.update({
  id: '/ranking/',
  path: '/ranking/',
  getParentRoute: () => MainRoute,
} as any)
const MainMypageIndexRoute = MainMypageIndexRouteImport.update({
  id: '/mypage/',
  path: '/mypage/',
  getParentRoute: () => MainRoute,
} as any)
const MainLearningIndexRoute = MainLearningIndexRouteImport.update({
  id: '/learning/',
  path: '/learning/',
  getParentRoute: () => MainRoute,
} as any)
const MainBattleIndexRoute = MainBattleIndexRouteImport.update({
  id: '/battle/',
  path: '/battle/',
  getParentRoute: () => MainRoute,
} as any)
const MainLearningQuestionRoute = MainLearningQuestionRouteImport.update({
  id: '/learning/question',
  path: '/learning/question',
  getParentRoute: () => MainRoute,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof PublicLoginRoute
  '/register': typeof PublicRegisterRoute
  '/': typeof PublicIndexRoute
  '/learning/question': typeof MainLearningQuestionRoute
  '/battle': typeof MainBattleIndexRoute
  '/learning': typeof MainLearningIndexRoute
  '/mypage': typeof MainMypageIndexRoute
  '/ranking': typeof MainRankingIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof PublicLoginRoute
  '/register': typeof PublicRegisterRoute
  '/': typeof PublicIndexRoute
  '/learning/question': typeof MainLearningQuestionRoute
  '/battle': typeof MainBattleIndexRoute
  '/learning': typeof MainLearningIndexRoute
  '/mypage': typeof MainMypageIndexRoute
  '/ranking': typeof MainRankingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_main': typeof MainRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_public/login': typeof PublicLoginRoute
  '/_public/register': typeof PublicRegisterRoute
  '/_public/': typeof PublicIndexRoute
  '/_main/learning/question': typeof MainLearningQuestionRoute
  '/_main/battle/': typeof MainBattleIndexRoute
  '/_main/learning/': typeof MainLearningIndexRoute
  '/_main/mypage/': typeof MainMypageIndexRoute
  '/_main/ranking/': typeof MainRankingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/register'
    | '/'
    | '/learning/question'
    | '/battle'
    | '/learning'
    | '/mypage'
    | '/ranking'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/register'
    | '/'
    | '/learning/question'
    | '/battle'
    | '/learning'
    | '/mypage'
    | '/ranking'
  id:
    | '__root__'
    | '/_main'
    | '/_public'
    | '/_public/login'
    | '/_public/register'
    | '/_public/'
    | '/_main/learning/question'
    | '/_main/battle/'
    | '/_main/learning/'
    | '/_main/mypage/'
    | '/_main/ranking/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MainRoute: typeof MainRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof MainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/register': {
      id: '/_public/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof PublicRegisterRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/login': {
      id: '/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_main/ranking/': {
      id: '/_main/ranking/'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof MainRankingIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/mypage/': {
      id: '/_main/mypage/'
      path: '/mypage'
      fullPath: '/mypage'
      preLoaderRoute: typeof MainMypageIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/learning/': {
      id: '/_main/learning/'
      path: '/learning'
      fullPath: '/learning'
      preLoaderRoute: typeof MainLearningIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/battle/': {
      id: '/_main/battle/'
      path: '/battle'
      fullPath: '/battle'
      preLoaderRoute: typeof MainBattleIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/learning/question': {
      id: '/_main/learning/question'
      path: '/learning/question'
      fullPath: '/learning/question'
      preLoaderRoute: typeof MainLearningQuestionRouteImport
      parentRoute: typeof MainRoute
    }
  }
}

interface MainRouteChildren {
  MainLearningQuestionRoute: typeof MainLearningQuestionRoute
  MainBattleIndexRoute: typeof MainBattleIndexRoute
  MainLearningIndexRoute: typeof MainLearningIndexRoute
  MainMypageIndexRoute: typeof MainMypageIndexRoute
  MainRankingIndexRoute: typeof MainRankingIndexRoute
}

const MainRouteChildren: MainRouteChildren = {
  MainLearningQuestionRoute: MainLearningQuestionRoute,
  MainBattleIndexRoute: MainBattleIndexRoute,
  MainLearningIndexRoute: MainLearningIndexRoute,
  MainMypageIndexRoute: MainMypageIndexRoute,
  MainRankingIndexRoute: MainRankingIndexRoute,
}

const MainRouteWithChildren = MainRoute._addFileChildren(MainRouteChildren)

interface PublicRouteChildren {
  PublicLoginRoute: typeof PublicLoginRoute
  PublicRegisterRoute: typeof PublicRegisterRoute
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicLoginRoute: PublicLoginRoute,
  PublicRegisterRoute: PublicRegisterRoute,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  MainRoute: MainRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
